#!/usr/bin/env bash

#MISE description "Install the Terraform HomeLab provider"

set -euo pipefail

OS_ARCH="$(go env GOOS)_$(go env GOARCH)"

echo ""
echo "📦 Installing Terraform HomeLab provider to \$GOROOT/bin ($GOROOT/bin)..."

go install .

# To use the provider with OpenTofu, we need to copy the binary to the tofu plugins directory
# The directory is usually located at ~/.local/share/opentofu/plugins/registry.terraform.io/<namespace>/<name>/<version>/<os_arch>/
# This is required so the provider will be discovered by OpenTofu when running terragrunt / terraform commands
# To configure where the provider could be found create a ~/.tofurc file with the following content:
# provider_installation {
#   dev_overrides {
#     "registry.terraform.io/abes140377/homelab" = "/Users/seba/.local/share/mise/installs/go/1.24.2/bin"
#   }
#
#   direct {}
# }

echo ""
echo "📦 Copying Terraform HomeLab provider to OpenTofu plugins directory..."
echo ""

# Create the directory structure
TARGET_DIR=~/.local/share/opentofu/plugins/registry.terraform.io/abes140377/homelab/0.1.0/$OS_ARCH
mkdir -p "$TARGET_DIR"

# Copy the provider binary from the Go bin directory(target of go install . from above) to the tofu plugins directory
cp -v \
     "$(go env GOBIN)/terraform-provider-homelab" \
     "$TARGET_DIR/terraform-provider-homelab_v0.1.0"

echo ""
echo "✅ Provider installation completed successfully!"
